
// This file has been generated by the GUI designer. Do not modify.
namespace NuGetPackageMakerAddin
{
	public partial class NuGetPackageMakerSettingWidget
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.Label label6;

		private global::Gtk.RadioButton defaultRadioButton;

		private global::Gtk.RadioButton checkCustomPath;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label8;

		private global::Gtk.Entry outputPathEntry;

		private global::Gtk.Button browsButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NuGetPackageMakerAddin.NuGetPackageMakerSettingWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "NuGetPackageMakerAddin.NuGetPackageMakerSettingWidget";
			// Container child NuGetPackageMakerAddin.NuGetPackageMakerSettingWidget.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("NuGet Package Maker Addin Setting");
			this.vbox5.Add(this.label6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.defaultRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use Default"));
			this.defaultRadioButton.CanFocus = true;
			this.defaultRadioButton.Name = "defaultRadioButton";
			this.defaultRadioButton.DrawIndicator = true;
			this.defaultRadioButton.UseUnderline = true;
			this.defaultRadioButton.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.vbox5.Add(this.defaultRadioButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.defaultRadioButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.checkCustomPath = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use Custom Path"));
			this.checkCustomPath.CanFocus = true;
			this.checkCustomPath.Name = "checkCustomPath";
			this.checkCustomPath.DrawIndicator = true;
			this.checkCustomPath.UseUnderline = true;
			this.checkCustomPath.Group = this.defaultRadioButton.Group;
			this.vbox5.Add(this.checkCustomPath);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.checkCustomPath]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("OutputDIrectory");
			this.hbox6.Add(this.label8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			// Container child hbox6.Gtk.Box+BoxChild
			this.outputPathEntry = new global::Gtk.Entry();
			this.outputPathEntry.CanFocus = true;
			this.outputPathEntry.Name = "outputPathEntry";
			this.outputPathEntry.IsEditable = true;
			this.outputPathEntry.InvisibleChar = '●';
			this.hbox6.Add(this.outputPathEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.outputPathEntry]));
			w5.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.browsButton = new global::Gtk.Button();
			this.browsButton.CanFocus = true;
			this.browsButton.Name = "browsButton";
			this.browsButton.UseUnderline = true;
			this.browsButton.Label = global::Mono.Unix.Catalog.GetString("Brows...");
			this.hbox6.Add(this.browsButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.browsButton]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(10));
			this.vbox5.Add(this.hbox6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox6]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
